"""Standalone unified entry points for SMAC-family environments."""

from .adapters import NormalizedEnvAdapter
from .handlers import (
    ActionBuilder,
    BuilderContext,
    BuildContext,
    DefaultNativeActionBuilder,
    DefaultNativeObservationBuilder,
    DefaultNativeRewardBuilder,
    DefaultNativeStateBuilder,
    DefaultObservationBuilder,
    DefaultRewardBuilder,
    DefaultStateBuilder,
    NativeActionBuilder,
    NativeObservationBuilder,
    NativeRewardBuilder,
    NativeStateBuilder,
    ObservationBuilder,
    RewardBuilder,
    RewardContext,
    StateBuilder,
    TrackedUnit,
    UnitFrame,
    UnitTeamFrame,
)
from .config import (
    ActionMode,
    CapabilityMode,
    OpponentMode,
    RewardPositiveMode,
    TeamInitMode,
    VariantName,
    VariantSwitches,
    default_switches,
    merge_switches,
)
from .env_factory import (
    BackendConfig,
    EnvFactoryConfig,
    UnifiedFactory,
    build_default_backend_registry,
    make_env,
)
from .core import (
    NativeStarCraft2Env,
    SC2EnvRawSession,
    SC2SessionConfig,
)
from .players import (
    EngineBotOpponentRuntime,
    HardScriptCompatibilityWrapper,
    OpponentEpisodeContext,
    OpponentPolicy,
    OpponentRuntime,
    OpponentStepContext,
    ScriptedOpponentConfig,
    ScriptedOpponentRuntime,
)
from .types import StepBatch

__all__ = [
    "BackendConfig",
    "ActionBuilder",
    "BuilderContext",
    "BuildContext",
    "DefaultNativeActionBuilder",
    "DefaultNativeObservationBuilder",
    "DefaultNativeRewardBuilder",
    "DefaultNativeStateBuilder",
    "DefaultObservationBuilder",
    "DefaultRewardBuilder",
    "DefaultStateBuilder",
    "EngineBotOpponentRuntime",
    "EnvFactoryConfig",
    "ActionMode",
    "CapabilityMode",
    "HardScriptCompatibilityWrapper",
    "NativeStarCraft2Env",
    "NativeActionBuilder",
    "NativeObservationBuilder",
    "NativeRewardBuilder",
    "NativeStateBuilder",
    "OpponentMode",
    "NormalizedEnvAdapter",
    "ObservationBuilder",
    "OpponentEpisodeContext",
    "OpponentPolicy",
    "OpponentRuntime",
    "OpponentStepContext",
    "RewardBuilder",
    "RewardPositiveMode",
    "RewardContext",
    "SC2EnvRawSession",
    "SC2SessionConfig",
    "ScriptedOpponentConfig",
    "ScriptedOpponentRuntime",
    "StateBuilder",
    "TeamInitMode",
    "StepBatch",
    "TrackedUnit",
    "UnitFrame",
    "UnitTeamFrame",
    "UnifiedFactory",
    "VariantName",
    "VariantSwitches",
    "build_default_backend_registry",
    "default_switches",
    "make_env",
    "merge_switches",
]
