"""Standalone unified entry points for SMAC-family environments."""

from .adapters import NormalizedEnvAdapter
from .handlers import (
    ActionHandler,
    DefaultActionHandler,
    DefaultObservationHandler,
    DefaultRewardHandler,
    DefaultStateHandler,
    HandlerContext,
    ObservationHandler,
    RewardHandler,
    StateHandler,
    TrackedUnit,
    UnitFrame,
    UnitTeamFrame,
)
from .config import (
    ActionMode,
    CapabilityMode,
    OpponentMode,
    RewardPositiveMode,
    TeamInitMode,
    VariantName,
    VariantSwitches,
    default_switches,
    merge_switches,
)
from .env_factory import (
    BackendConfig,
    EnvFactoryConfig,
    UnifiedFactory,
    build_default_backend_registry,
    make_env,
)
from .core import (
    SMACEnv,
    SC2EnvRawSession,
    SC2SessionConfig,
)
from .players import (
    EngineBotOpponentRuntime,
    HardScriptCompatibilityWrapper,
    OpponentEpisodeContext,
    OpponentPolicy,
    OpponentRuntime,
    OpponentStepContext,
    ScriptedOpponentConfig,
    ScriptedOpponentRuntime,
)
from .types import StepBatch

__all__ = [
    'BackendConfig',
    'ActionHandler',
    'DefaultActionHandler',
    'DefaultObservationHandler',
    'DefaultRewardHandler',
    'DefaultStateHandler',
    'EngineBotOpponentRuntime',
    'EnvFactoryConfig',
    'HandlerContext',
    'ActionMode',
    'CapabilityMode',
    'HardScriptCompatibilityWrapper',
    'SMACEnv',
    'ObservationHandler',
    'OpponentMode',
    'NormalizedEnvAdapter',
    'OpponentEpisodeContext',
    'OpponentPolicy',
    'OpponentRuntime',
    'OpponentStepContext',
    'RewardHandler',
    'RewardPositiveMode',
    'SC2EnvRawSession',
    'SC2SessionConfig',
    'ScriptedOpponentConfig',
    'ScriptedOpponentRuntime',
    'StateHandler',
    'TeamInitMode',
    'StepBatch',
    'TrackedUnit',
    'UnitFrame',
    'UnitTeamFrame',
    'UnifiedFactory',
    'VariantName',
    'VariantSwitches',
    'build_default_backend_registry',
    'default_switches',
    'make_env',
    'merge_switches',
]
